### ISSUE TITLE
some questions need help

### ISSUE THREAD

**Issue by SmallMunich** [wangx1996/Multi-Object-Tracking#2]
Hi, @wangx1996 . Thanks for supply this code. Here, I have some questions needs your some reply.

1. I clone this code, and using catkin_make passed. but when I run roslaunch track.launch， here appears some error in terminate.

`setting /run_id to e811c1b4-66e5-11ec-af2b-40b07680d35e
process[rosout-1]: started with pid [19543]
started core service [/rosout]
process[tracking_node-2]: started with pid [19549]
process[rviz-3]: started with pid [19551]
222+++++++++++++++++++++++++++
[tracking_node-2] process has died [pid 19549, exit code -11, cmd /media/holo/B834B57734B538E8/Multi-Object-Tracking/track_ws/devel/lib/mot_tracking/tracking_node __name:=tracking_node __log:=/home/holo/.ros/log/e811c1b4-66e5-11ec-af2b-40b07680d35e/tracking_node-2.log].
log file: /home/holo/.ros/log/e811c1b4-66e5-11ec-af2b-40b07680d35e/tracking_node-2*.log
`

222++++ is debug message, only located in main(). example is here:

`int main(int argc, char** argv)
 {
  ros::init(argc, argv, "vision_node");

  ros::NodeHandle nh;

  std::cout << "222+++++++++++++++++++++++++++" << std::endl;
  `image_transport::ImageTransport it(nh);`
  std::cout << "222.5+++++++++++++++++++++++++++" << std::endl;
  image_transport::Publisher pubimage = it.advertise("/mot_tracking/image", 1);

}
`

I confused why not go passed `image_transport::ImageTransport it(nh);`.

2. about this data path:

---/xxx/0020
      |--velodyne/0020
      |--oxts/
      |--label_02/

Is it right?

**Comment by SmallMunich** [comment]
solve it, because of different boost thread will coredump. I use boost version is 1.65.1.

**Comment by flora077** [comment]
hi! After you use 1.65.1,can you successfully run this project now?
